package vn.remove.photo.content.qwer.Descripition;

public class DayDescrip {
    public String[] des_day = {"Your daily numeroscope is based on your personal number for that day. It tells you what type of energy or theme you can expect during the course of the day. This can help you decide what you should pursue or avoid to make the most of your day.\nTo determine your daily personal number we added today’s number to your personal month number.",
            "Today is a one day for you. That means it’s a good time to start something new. If you’ve been working on a project or problem for some time, today can bring new insights and vigour to your established endeavours.\nTry to remain open to feedback though. With one energy we tend to focus on ourselves, and that can make us headstrong. This can have negative consequences if you ignore some good advice.\nGenerally speaking this is a good day to focus on yourself and your personal goals. Overall you can look forward to an inspiring day filled with personal advancements.",
            "Yay! It’s a two day!\nToday is all about teamwork and getting along with others. If you haven’t had time for friends or family recently today is a great time to catch up. With the two energy, your communication skills are in peak form so any interactions will go well.\nYou won’t want to be alone though, and this can make you extra clingy. If you’re prone to becoming too attached to people, or relying on others too heavily today can have its challenges.\nBut it’s just for today so what the heck ;)",
            "Three days are all about releasing your inner creative potential. So don’t let anything stand in your way!\nYou’ll want to have a lot of fun today, and that’s a good thing. We all need to let our hair down from time to time.\nJust make sure your obligations are taken care of. You don’t want to be creative and amazing at the expense of your own obligations. It will be difficult to push through and get the necessary done before you go off on a creative adventure, but you’ll be glad you did.",
            "Four days are all about laying foundations and getting things done. You’ll be drawn to the boring routine of getting your life in order today.\nOf course this can be quite an exciting time as you lay the foundation for the future. But your friends and family are going to be taking a back seat for the day. You’ll be too busy making your mark on the world to spend time with frivolities like small talk and social gatherings.\nThat being said, once you’ve got your affairs in order there may be some time left to have some fun.",
            "Pack your goodie bag cuz today you’re off on an adventure!\nToday’s five energy is all about exploring the uncharted territories of your life. If you’ve been waiting for excitement and exhilaration today is the day it’s going to show up. So don’t hold yourself back from doing the things you don’t normally do.\nDon’t force yourself to do the mundane today. To make the most of today’s energy you need to follow your heart and throw caution to the wind. You can always get back to the responsibilities of real life tomorrow. Just don’t go too far overboard!",
            "If you’ve been craving some tlc and family time today is the day to do it.\nSix days are perfect for snuggling up in your favourite spot and chatting to your favourite people. Of course you could also decide to finish that DIY project to make your house a bit more homey.\nAnything that’s centred around family and building your home or future is a good use of your time today. But try not to become too emotionally invested in today’s projects. Sometimes six energy can make us emotional wrecks. That being said, curling up in a blanket fort for one night never hurt anyone…",
            "Seven energy is going to awaken the deep thinker in you today.\nEven if you aren’t a philosopher by nature, you’ll find yourself wondering why things are the way they are today. With all the deep thinking you might find it difficult to concentrate on everyday tasks and get things done…\nBut on the flip side, it’s always good to know where you’re heading and what you really want from life.\nSo let your mind wander a bit, even if you end up deciding that you’re on the best course, it’s better to know than wonder forever.",
            "Eight energy is all about the infinite and how things fit together.\nIf you’ve been working on a big project today is the day to take a step back and reassess all the minor details. You’ll be able to see the bigger picture more clearly today.\nSo whether you’ve been focused on your career, love life, or home, after today you’ll have a much clearer idea of what needs to get done – and what can be thrown in the waste bin. Not every dream needs to become a reality and today you’re going to see what’s working and what isn’t.",
            "Today’s nine energy marks the end of a cycle.\nIf you’ve been working hard towards a goal you can expect some good news today. At the very least you’ll hear that you made good progress – at best you’ll have reached the goal.\nBut nine energy is also about seeing things from a higher level of perception. So even if you haven’t reached your destination yet, today will give you great insights about what it is you really want to achieve. Sometimes it’s okay to change our goals for the greater good and if that’s the case for you, that change is going to happen today."

    };
}
