package vn.remove.photo.content.qwer.Descripition;

public class MonthDescip {
    public String [] mon_des={
             "Your monthly personal number determines the quality of energy you’ll experience throughout a month. It’s a low-key energy that has a mild, yet lasting effect on the quality of your experiences. We’ve determined your personal month number by adding this month’s number to your personal year number.",
             "This month awakens the one energy in your life. There is a big focus on increasing your personal sense of power. You have been given a handful of seeds to sow in your life. As the month progresses you’ll be able to see those seeds grow.\nJust be careful not to become too caught up in your own drives. This month’s one energy is all about focusing on personal power, just make sure you’re not stepping on others to get ahead.\nThat being said, you can look forward to new beginnings and adventures this month. If you’ve been waiting for the perfect time to start something new, like a family or business venture, this is the month to start acting on those plans. As long as you keep others in mind, this can be a very fortuitous month for you.",
             "During a two month you can look forward to lots of positive interactions with other people. Two energy is all about partnerships. Whether you’re getting closer to friends, family, colleagues or that special someone – this month you’ll be making progress in your interpersonal communication.\nOn the downside this can mean that you get so invested in your relationships that you forget to pay attention to the other aspects of your life.\nOn the plus side – life becomes a whole lot smoother when you know the right people. In fact, our sense of well-being depends on how well our relationships are going. So while you might face some heated moments with people this month, by the end of it you’ll be happy you put in the effort to make your relationships work.\nPs. Remember relationships don’t have to be romantic. This month is about building ALL the relationships in your life – even work relationships.",
             "Three is an interesting energy.\nOn the one hand it’s all about having fun and saying “que será será”.\nOn the other hand it’s about coming up with the most profound and life-changing ideas of your life.\nSo how do these two seemingly opposing forces come together this month?\nWell your creativity is directly linked to your freedom. If you express yourself freely and let your inhibitions go you’re much more likely to be creative.\nOn the other hand, if you walk around with a dutiful sense of what’s right and wrong you’re restricting your creativity.\nSometimes we need to let our guard down and do the things we wouldn’t normally do. This helps us to see the world from a different perspective. And new perspectives lead to new ideas. So let yourself have some fun this month. Even though it might not be your style, it can give you some great ideas to make your future more enticing that you ever thought possible.",
             "Get ready to buckle down and get things done – four months are all about putting in the effort.\nThroughout the month you might feel like fundamental parts of your life are changing. That’s okay. As long as you keep working towards your goals everything will fall in place in the end.\nYou might find that your life restructures itself this month. Four energy is about structure and stability, but sometimes it means that those aspects of your life are going to be tested. So sometimes four months can be unpredictable.\nBut generally speaking this month should be focused on hard work, perseverance – Regardless of whether you’re building on existing structures or whether you’re starting from scratch. You’ll be hard at work getting things done. And by the end of it you’ll have a much clearer idea of where your life is heading.",
             "Get ready for an interesting month! Five energy is all about exploring new things. You’ll be drawn to doing things you don’t normally do to satisfy the adventurer in you.\nWhile five energy doesn’t necessarily indicate travel, this is a good month to go on a holiday or adventure. So if you’ve been itching to go somewhere it’s time to book those tickets! But be warned, it’s going to be an interesting trip so pack light and make sure you always have a way of getting back home.\nIf you’re less of an adventurer you can also satisfy your need to explore uncharted territories in the comfort of your own home. Homebodies are likely to try new things in their life this month. Think exotic cuisine, a change in routine or finally getting round to reading that new book…\nWhichever way you decide to indulge in your dreams this month, try to keep moderation in mind. Too much of a good thing is hardly ever a good thing.",
             "It’s time to retreat to your happy place this month. Six energy is all about physical comfort and creating a good environment for yourself.\nThis is a manifestation month for you. Six energy is all about bringing ideas to life. So you can look forward to spending time bringing your dreams to life this month. And while six energy is mostly focused on home life, your manifestation powers aren’t limited to DIY projects. This is also a good month for things like new business ventures and even new relationships.\nIn fact, building bonds with people is a big theme for you this month. You’ll feel more caring and considerate towards others than usual. But don’t let your emotions get the better of you. Remember, not everyone is experiencing the same as you, so if they’re colder and more distant than you’d like don’t take it personally.",
             "It’s time to put your thinking cap on – this month is all about mental powers and discernment. Your brain will be in overdrive this month, so make sure you keep it occupied.\nSeven energy is usually very anti-social. You’ll be so caught up in your own thoughts that it can be difficult to concentrate on what others are saying. But, if you find someone that’s on the same wavelength as you, you’ll find it difficult to stop sharing ideas.\nGenerally speaking seven months aren’t great for making physical progress either. Rather you’ll find yourself thinking of how you possibly could make changes in your life, without actually executing those ideas. Instead you’ll find yourself planning each and every step, including everything that could go right and wrong. So when you do get round to doing whatever you’re daydreaming about this month you’ll know exactly what to do – and what not to do.",
             "This month is going to be a busy one, so get ready! Eight energy is about infinite possibilities, but in a completely realistic setting. So your critical mind is going to be working in overdrive to bring the bigger picture to life just the way you want it.\nYou’ll be focusing on every tiny detail this month and trying to make sure that everything works together seamlessly. In a way eight energy brings out the engineer in each of us. If you think of your life as a giant machine working to fulfil a purpose, eight energy helps you to see how each part of the machine works together to bring your dreams to life.\nIf some aspect of your life isn’t fitting into your master plan, this is the month to work on getting out of that rut and back onto the superhighway towards true fulfilment and happiness.",
             "Congratulations are in order. In some way or another you’re going to be a winner this month.\nNine energy marks the end of an energy cycle. Whatever you’ve been focused on for the last year or so is going to come to a crescendo this month. Unfortunately nine energy doesn’t differentiate between good and bad like we do. So you could end up being the winner of a negative manifestation if you’ve been playing the victim card all this time.\nThat being said, you’ll be getting exactly what you asked for. So if you don’t like what you get this month it’s time to take a good hard look at why you’re getting what you’re getting.\nThe flip side of nine energy is that it’s going to give you some perspective and insight into why things are the way they are. So keep your eyes peeled for clues on how to make the next energy cycle better. Life never stops, and this month is all about learning how you can improve during the next cycle. So it’s a definite win, but it’s not the end of the race."

    };
}
