package vn.remove.photo.content.qwer.Descripition;

public class YearDescrip {
    public String[] year_des = {
             "Your personal year number gives you an idea of the energies that are going to affect your life throughout the year. This is a very subtle influence, but it has massive potential. When you act in line with your personal year energy you’re sure to make the most of what you’re given, even if it takes time to see the results.\nTo calculate your personal year number we took your birth day and birth month numbers and added it to this year’s number.",
            "\"You’re going through a 1 personal year. That means you’re just starting out on your yearly energy cycle. Things can feel new and exciting this year, but you can also be faced with residual karma from previous cycles. So, while this year is all about new beginnings, it’s also about applying the wisdom you’ve gained throughout your life to put an end to negative actions and their consequences.\n" +
                    "                \"career\": \"A one year is an excellent time to focus on your career. One energy is associated with natural leadership qualities. You’ll also be able to inspire others with your vision and enthusiasm. A one year is one of the best years to focus on your career and work towards a promotion or business goal.\",\n" +
                    "                \"love\": \"If you’re single, expect it to stay that way. Unfortunately one years aren’t the best time to start a relationship. One energy is very self-centred. So you might find it difficult to build solid, lasting connections with new people.\\nThat being said, if you’re already in a relationship this is a good year to take things to the next level. As long as you communicate openly with your partner and listen to their needs you will be able to grow stronger together.\",\n" +
                    "                \"relationship\": \"One energy can put a lot of strain on relationships. With everything feeling new and exciting, you’ll be tempted to spend more time working on personal goals. This can be a very good thing for you - but unfortunately it doesn’t leave a lot of time for other people in your life. This year you’re going to have to make an active effort to stay in touch with other people. Otherwise you might find yourself celebrating your personal victories alone by the end of the year.\"\n" +
                    "",
            "\"Two years are a great time to bring this together and spend time building relationships. The number two is associated with any and all binaries. So you’ll have a greater sense of what’s right and wrong. But at the same time you’ll also be open to changing your own mind if you’re presented with good evidence.\",\n" +
                    "                \"career\": \"This is the year where you might change the way you go about doing business. With the relational influences of a two year you’re likely to start seeing things slightly differently. To really get ahead in your career this year it’s a good idea to talk to experts in your field to get a good idea of what works and what doesn’t. This year is all about sharing ideas to come to the best solutions.\",\n" +
                    "                \"love\": \"When it comes to romance two years are a great time to start a new relationship. You’re amiable and open to criticism this year. Obviously that doesn’t mean you’ll turn into a doormat for just anyone to walk over. But generally speaking you’ll be open to learning about how others perceive the world and that can change the way you look at things – which is a great foundation to build new and lasting relationships.\",\n" +
                    "                \"relationship\": \"During this year you’re going to be faced with a lot of conflicting evidence. For example you might get to know a deep dark secret about someone that changes the way you see them as a person. That being said, two years are about finding the middle ground. So even though you might not agree with everything someone does, you’ll still be able to see their value as a perfectly imperfect human. So while this year might challenge some relationships in your life, by the end of it you’ll know exactly where you stand with the people in your life.\"\n" +
                    " ",
            " \"Three years are perfect for unleashing your creative potential. You’ll be drawn towards the fun side of life. You know, that part of life where you don’t quite know what to expect, but you feel drawn to it like a moth to a flame. So follow your heart and don’t put too much “real world” pressure on yourself.\",\n" +
                    "                \"career\": \"Creativity is the name of the game this year, and your career is no exception. You’re likely to come up with innovative solutions to long-standing problems at work. So let your creative juices flow. Fair enough, not every idea you come up with is going to work right off the bat, but with a little refinement even the most outrageous plans can become perfect solutions.\",\n" +
                    "                \"love\": \"Three is a crowd. And you’re so drawn to sharing ideas and passions that it can be a bit difficult to stay tied down to one person this year. If you aren’t in a relationship yet, you’ll be meeting your fair share of candidates, although choosing that one special someone is easier said than done. If you’re already in a relationship use this year’s creative energies to make the relationship something truly special. If you don’t spend energy on making your current relationship spectacular your eye is likely to wander towards other suitable candidates, so be careful.\",\n" +
                    "                \"relationship\": \"Your social life has never been more exciting. Which is a good thing. When we share ideas and passions with the people around us we can get valuable insights into how the universe and life really works. But try not to become too caught up in sharing ideas. You need to implement your ideas to manifest your dreams. So keep a good balance between your urge to dream big and your ability to walk your talk.\"\n" +
                    "  ",
            "\"It’s time to put the pedal to the metal. Up to now you’ve had some fantastic ideas and you’re on the right track. But now is the time to prove yourself. Do you have what it takes to get the job done? Of course you do. You just need to commit to your purpose and push through the growing pains.\",\n" +
                    "                \"career\": \"Four energy is great for your career. You’ll want to work hard and prove your worth this year. You’re like the Energiser bunny – unwilling to back down from a challenge and willing to do whatever it takes to prove your worth. Just make sure you don’t burn yourself out in the process.\",\n" +
                    "                \"love\": \"Four energy isn’t the best time for romance – unless romance is a fundamental part of who you are. Four energy is all about building towards a better future. So if your idea of the perfect life includes a spouse and kids, it’s likely that you’ll make that happen this year. But if you’re more focused on other things at the moment, don’t expect any miracles in this department.\",\n" +
                    "                \"relationship\": \"Relationships that work will probably keep on working, but those that don’t might not stand the test of time. You’ll be very focused on certain structures in your life this year. And if someone doesn’t fit into the structures you want to build for yourself you won’t think twice before cutting them out of your life. On the positive side this means you won’t be wasting your time on people that just don’t get you. On the other hand, just because they don’t get you right now doesn’t mean they won’t understand you in the future… So don’t burn all your bridges just yet.\"\n" +
                    "  ",
            "\"It’s adventure time! You can look forward to unexpected things this year. From traveling to exotic destinations to doing things you never thought possible – five years are all about pushing the boundaries and carving a new way of life. But don’t be surprised if everything doesn’t turn out the way you thought it would.\",\n" +
                    "                \"career\": \"Five energy isn’t necessarily the best career wise. You’ll be drawn to adventure more than routine – so getting mundane tasks done can be a bit of a challenge. That being said, this is a great time to broaden your horizons and stretch yourself a bit further than you thought you could go. As long as you keep repeating “nothing ventured nothing gained” you should be able to make the most of this adventurous energy.\",\n" +
                    "                \"love\": \"While five years are all about finding a new appreciation for the world, this might not involve a special someone. Five energy can make it difficult to settle down. So if you’re in a relationship you could be faced with multiple temptations this year. On the other hand, if you’re a free agent this is a great time to see what the world has to offer. Either way, you’ll be drawn towards exciting instead of drab. So make sure your priorities are in order before you make a spur of the moment decision you’ll regret later.\",\n" +
                    "                \"relationship\": \"Five energy is all about excitement and exploration. You’ll probably find yourself making plenty of new friends. But whether they’re going to stick with you is a different story. Lots of people will be drawn to the excitement of your life this year. So don’t be surprised if you find most of them going their own way once the year has played itself out.\"\n" +
                    " ",
            "\"It’s time to focus on the things you want to bring to life. Six years are the perfect time to focus on making your dreams a reality. This can be easier said than done though. So make sure you’re putting the right kind of effort into your life. Whatever you’re putting in is going to be manifested this year, whether that’s positive or negative energy.\",\n" +
                    "                \"career\": \"Six energy is very focused on bringing ideas to life. But on the other hand it’s also more focused on your personal life than your career. If you can find a way to incorporate your personal dreams into your career you’re likely to succeed this year. But you’re also prone to becoming so enmeshed in your personal goals that you forget all about your job. Try to keep the balance.\",\n" +
                    "                \"love\": \"This year you’ll be super focused on creating a comfortable home-life for yourself. If a steady partner forms part of that picture for you, you can look forward to manifesting a good relationship. But don’t be surprised if you don’t meet the person of your dreams. In the end this year is about making yourself happy and doing the things you think are important, so if an intimate relationship isn’t your idea of heaven on earth chances are it isn’t going to happen.\",\n" +
                    "                \"relationship\": \"Romantic relationships aside, six energy is quite a social one, especially when it comes to family. You can look forward to sharing good times with good people. Especially if you share the same values and goals as the people you’re interacting with. Unfortunately those that don’t share your passions and worldview will probably be left behind.\"\n" +
                    "  ",
            "  \"During this year you’re going to be forced to think about where you’re heading and why you’re heading in that direction. Your convictions will be tested. And you’ll be wondering about why your life is the way it is a lot of the time. Try not to become too involved in your own thoughts though, the world has a lot to offer so don’t let your mindset keep you from seeing all the opportunities on offer.\",\n" +
                    "                \"career\": \"Seven years are all about mind power. If you’re focused on making advances in your career you’ll probably be able to spot opportunities as soon as they make an appearance. On the other hand, if you’re so caught up in how much still needs to get done those opportunities are sure to pass by unnoticed.\",\n" +
                    "                \"love\": \"Unless your focus is on building a solid romantic relationship, chances are this will be the last thing on your mind. The good thing is that you’ll be so focused on other things that you won’t even miss having a partner in crime. If you’re already hitched do make sure you spare a thought for your significant other before they become a distant memory.\",\n" +
                    "                \"relationship\": \"If someone doesn’t stimulate you on an intellectual level you aren’t going to find much time for them this year. Your inner philosopher is hard at work trying to piece together the puzzle that is your life. So don’t be surprised if you completely forget about the people that aren’t actively adding value to your life. Try not to be too judgemental though. Your own sense of value will probably change throughout the year, and so will your social requirements.\"\n" +
                    " ",
            "\"Eight years are the make or break years of your yearly energy cycle. This year’s energy is going to help you see the bigger picture of where your life is heading. If you pick up on the parts of your life that still need a bit of work you’re sure to make the most of the current cycle. But if you fail to notice the pieces of the puzzle that aren’t quite fitting with your destiny you can miss some valuable opportunities.\",\n" +
                    "                \"career\": \"This is a great year to work on personal development to get ahead in your field. While eight energy is all about the infinite, it’s mostly about how you fit into the infinities of life. So if your goal is to become a master in your field, this is a great year to focus on building the skills you need to be the best.\",\n" +
                    "                \"love\": \"Whether you’re hitched or not, this year is going to be filled with a few challenges. Not that any relationship doesn’t have its ups and downs. But this year the challenges are real opportunities for growth. The more you can learn through the mirror of an intimate relationship the more accomplished you’ll feel by the end of the year.\",\n" +
                    "                \"relationship\": \"Your focus is on becoming the best version of yourself. So don’t be surprised if you leave the haters in the dust. On the other hand, making friends with your enemies is a sure way to get ahead, so there’s a good chance you’ll use your charisma and influence to win people over this year – especially if there’s a chance you can benefit from the relationship.\"\n" +
                    " ",
            "\"Nine years mark the end of an energy cycle and as a result you’ll feel like a superhero most of the time. Your goals are going to be met and if you’re being 100% authentic and true to your Higher Purpose chances are you’ll experience some miraculous manifestations throughout the year. Just make sure you keep the bigger picture in mind, because this high isn’t going to last forever.\",\n" +
                    "                \"career\": \"This is the year to shoot for the stars in any aspect of your life – your career is no exception. You’ll probably start the year off on a good note regardless of your expectations for the rest of the year. If you play your cards right you’ll be going nowhere except up from there – just don’t get too cocky, you’ll still need to put in the effort to reap the rewards.\",\n" +
                    "                \"love\": \"Your personal development is going to reach a new level this year which means your love life is sure to follow suit. You’re at a point in your life where you’re content with where you are. Even if you haven’t reached all your goals you know where you’re heading and what you want from life. This quiet confidence will make you irresistible to the right person.\",\n" +
                    "                \"relationship\": \"While most of your relationships should evolve along with the rest of your life don’t be surprised if you pick up a couple of haters along the way. When we reach new heights in our lives people always seem to get a little bit jealous. Try not to take it too personally. Don’t read too deeply into the criticisms and only change the things you agree need to change. This is your year in the spotlight, so don’t let the haters steal that from you by making you doubt your own success.\"\n" +
                    "  ",









    };
}
